title: "Dhruti Brahmbhatt"
description: "Bioinformatics · Clinical Informatics · Molecular Profiling"
url: "https://tinks2712.github.io"
baseurl: ""

# Minimal Mistakes theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

logo: /assets/img/profile.jpg
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  
author:
  name: "Dhruti Brahmbhatt"
  avatar: "/assets/img/profile.jpg"
  bio: "Research Associate (UTMB). Single-cell + bulk RNA-seq, molecular profiling, and data storytelling."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:brahmbhattdhruti07@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/tinks2712"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/dhruti-brahmbhatt-5379931b7/"
