title: "Dhruti Brahmbhatt"
description: "Bioinformatics · Clinical Informatics · Molecular Profiling"
url: "https://tinks2712.github.io"
baseurl: ""   # do not change for username.github.io sites

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# Plugins supported on GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Branding (optional logo shown in header & metadata)
logo: /assets/img/avatar.jpg

# Author box (shown on pages where you set `author_profile: true`)
author:
  name: "Dhruti Brahmbhatt"
  avatar: "/assets/img/avatar.jpg"   # <= exact path & filename you uploaded
  bio: "Research Associate (UTMB). Single-cell & bulk RNA-seq, molecular profiling, and data storytelling."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:brahmbhattdhruti07@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/tinks2712"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/dhruti-brahmbhatt-5379931b7/"

# Simple, clean permalinks
permalink: /:title/
